Quick Sort
Prem-Kumar-Dev/hacktoberfest2024-project pull request #21
Opened 2024-10-10 15:41 UTC by bhaviya18

I have added quick sort algorithm in C language
fixed issue #19

2024-10-10 15:43 UTC, Prem-Kumar-Dev approved these changes

2024-10-10 15:44 UTC, Prem-Kumar-Dev requested changes
@bhaviya18 kindly remove .vscode folder files from the commit

2024-10-10 16:03 UTC, bhaviya18 commented
@Prem-Kumar-Dev I removed the said files. You can review them.

2024-10-11 13:21 UTC, Prem-Kumar-Dev approved these changes

2024-10-11 13:21 UTC, merged